server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    driverClassName: org.postgresql.Driver
    username: pjay
    password: 1234
#  h2:
#    console:
#      enabled: true
#  sql:
#    init:
#      encoding: UTF-8
#      mode: always
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql
  jpa:
    defer-datasource-initialization: true
    open-in-view: false # 트랜잭션 범위 밖에서 영속성 컨텍스트를 유지할지 여부
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  output:
    ansi:
      enabled: always

logging:
  level:
    '[com.pjb.topicboard]': debug